#!/usr/bin/env bash
# Install nginx server and configure the index.html
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
