#!/usr/bin/env bash
# Install nginx server and configure the index.html
apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | tee /var/www/html/index.html
service nginx restart
