#!/usr/bin/env bash
# Install nginx server and configure the index.html
apt-get update
apt-get -y upgrade
apt-get -y install nginx
echo "Holberton School" | tee /var/www/html/index.nginx-debian.html
service nginx restart