#!/usr/bin/env bash
# Configures a brand new Ubuntu system.

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/new_404.html

redir="rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;\n"
sed -i "/server_name _/a $redir" /etc/nginx/sites-available/default

err='error_page 404 /new_404.html; \nlocation = /new_404.html \n{\nroot /var/www/html/;\ninternal; \n}'
sed -i "/server_name _/a $err" /etc/nginx/sites-available/default

sudo sed -i '/location \/ {/a \\t\tadd_header X-Served-By $HOSTNAME;\n' /etc/nginx/sites-available/default

service nginx restart