#!/usr/bin/env bash
# Installs and configures HAProxy (to be used in the load balancer server).
apt-get -y update
apt-get -y install haproxy=1.6.\*

echo -e "
backend web-backend
    balance roundrobin
    server web-01 34.139.183.139:80 check
    server web-02 35.196.251.46:80 check

frontend http
    bind *:80
    mode http
    default_backend web-backend
    " >> /etc/haproxy/haproxy.cfg

service haproxy restart