#!/usr/bin/env bash
# Script to install and configure HAproxy
sudo apt-get -y update
# Install HA Proxy
sudo apt-get -y install haproxy
# Enable to HA Proxy to start at boot
sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo echo "
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend
 backend web-backend
	balance roundrobin
	server 2383-web-01 34.139.183.139:80 check
	server 2383-web-02 35.196.251.46:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
