#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays To infinity and beyond indefinitely
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

FILE=/var/run/holbertonscript.pid
echo $$ > $FILE
trap "echo I hate the kill command ; sudo rm ""$FILE"" ; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "sudo rm ""$FILE"" ; exit" SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
