#!/usr/bin/env bash

echo $$ > /var/run/holbertonscript.pid
trap 'echo I hate the kill command ; sudo rm '"$FILE"' ; exit' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'sudo rm '"$FILE"' ; exit' SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done