#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

while IFS=':' read user pass uid gid uid_info home_dir com; do
  echo "The user $username is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $password,"\
  "more info about the user here: $info"
done < "/etc/passwd"
