#!/usr/bin/env bash
# Changes localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8.
cp /etc/hosts ~/hosts.bak
cp /etc/hosts ~/hosts.copy
sed -i 's/^127.0.0.1/127.0.0.2/g' ~/hosts.copy
echo "8.8.8.8	facebook.com" >> ~/hosts.copy
cp -f ~/hosts.copy /etc/hosts
