#!/usr/bin/env bash
# Configures nginx to run as non-root (nginx user), and to listen on port 8080
pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
